import React from "react";

export default function TermsOfService() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl flex-1">
      <div className="bg-card p-8 md:p-12 rounded-3xl border border-border shadow-sm prose prose-slate dark:prose-invert max-w-none">
        <h1 className="text-4xl font-extrabold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: June 2026</p>

        <p className="lead text-xl">
          Welcome to HirePilot-AI. These Terms of Service govern your use of our website and AI-powered career operating system. By accessing our services, you agree to these terms.
        </p>

        <hr className="my-8 border-border" />

        <h2 className="text-2xl font-bold mt-8 mb-4">1. Acceptance of Terms</h2>
        <p>
          By creating an account or otherwise using HirePilot-AI, you agree to be bound by these Terms and our Privacy Policy. If you do not agree, you may not use our services.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">2. Description of Service</h2>
        <p>
          HirePilot-AI provides AI-driven tools for job seekers, including resume parsing, cover letter generation, interview coaching, and application tracking. We reserve the right to modify or discontinue the Service at any time.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4">3. User Responsibilities</h2>
        <p>You agree to:</p>
        <ul className="list-disc pl-6 space-y-2 mb-6">
          <li>Provide accurate, current, and complete information during registration.</li>
          <li>Maintain the security of your password and account.</li>
          <li>Not use the Service for any illegal or unauthorized purpose.</li>
          <li>Not upload viruses or malicious code.</li>
        </ul>

        <h2 className="text-2xl font-bold mt-8 mb-4">4. Intellectual Property</h2>
        <p>
          All content generated by HirePilot-AI's AI using your input (such as your modified resume or generated cover letters) belongs to you. The underlying technology, design, and source code of HirePilot-AI remain our exclusive property.
        </p>
      </div>
    </div>
  );
}
